= Build & run

== How to build

----
g++ -o main main.cpp `sdl2-config --libs --cflags` -lSDL2_image
----

== How to run

----
xhost +local:docker
sudo docker run --rm -it -e DISPLAY=${DISPLAY} -v /tmp/.X11-unix:/tmp/.X11-unix -v $(pwd):/home/jim/test sdl2
----

== Binary files format

=== Level

List of tiles indices (in the tileset) as shorts (two bytes per index, little endian). The dimension (i.e. width) of the
level is stored outside of the file. For now.

=== Animations

The _period_ of the animation is the number of tiles making it up. It is stored on one byte. The _duration_ of the
animation is how many ticks pass before the animation goes to the next step / tile. Stored on the next byte. Then are
the tiles indices (in the tileset) as shorts (two bytes per index, little endian).

== Editor

Move around using the right mouse button. Select a tile to place by left-clicking on it in the tileset view. Place a
tile by left-clicking on a location in the level view. Save the level by pressing `S`.

== TODOs

. Editor: fix performance issue (use pyglet's sprites)
. Two layers of tiles
. Editor: resizable tileset window
