= FlatKiss
:1: https://en.wikipedia.org/wiki/KISS_principle

image::https://drive.google.com/uc?export=download&id=1RkDHVplmHKQtxRa-1fiRS8aFoBad-_Px[Preview]

FlatKiss is a 2D tile based toy game engine written in C++.

== Paradigm

First and foremost the mindset driving this project is *_simple_*. It embraces the {1}[KISS] principle. Simplicity comes
before performance / optimization. Simple is different from easy. It is easy to complicate things, but hard to make them
simple. In this project, before implementing anything the question which is asked is: "_Is this simple?_". If it is not,
then revamp it.

Concerns about performance only come after. When the project starts behaving slowly, *then* things can be torn to
accomodate performance. This is C++ with SDL, so unless doing crazy things performance often comes out of the box.

== Terminology

FlatKiss is spelled like this depending on the chosen case:

. FlatKiss
. flatkiss
. FLATKISS

IMPORTANT: No hyphen `-` or underscore `_` in the name, ever.

== Find your way in the documentation

link:doc/architecture.adoc[Architecture]:: Understand how the project works
link:doc/environment.adoc[Environment]:: Setup your environment for development
link:doc/test.adoc[Test]:: Build the project with the CI, find useful resources for testing
link:doc/development.adoc[Development]:: Learn how to start working on the project
link:doc/release.adoc[Release]:: Publish new versions of the project

== Running the engine

The simplest course of action is to download the artifacts from the latest CI run.

WARNING: As of now only a Linux version is provided by the CI. For other platforms, refer to the documentation pages
linked in the previous section.

Go to the _Actions_ tab in the GitHub repository page, select the last workflow run and download the artifacts. Unzip
them in a common directory (the configuration file must be in the same directory as the executable), grant execution
permissions to the program (`chmod u+x ...`) and run it.

NOTE: It may be that the artifacts have expired if the last workflow run occurred too long ago. In that case a new one
must be ran. They can be triggered manually but this requires write permission on the repository. For those who do not
have it, forking the repository should work just fine.

== Status

I am not actively working on the project. I come back to it from time to time for improving a thing or two. There are
still various issues to address, which can be found in link:doc/development.adoc[Development].
