= FlatKiss
:1: https://en.wikipedia.org/wiki/KISS_principle

FlatKiss is a 2D tile based game engine.

== Paradigm

First and foremost the mindset driving this project is *_simple_*. It embraces the {1}[KISS] principle. Simplicity comes
before performance / optimization. Simple is different from easy. It is easy to complicate things, but hard to make them
simple. In this project, before implementing anything the question which is asked is: "_Is this simple?_". If it is not,
then revamp it.

Concerns about performance only come after. When the project starts behaving slowly, *then* things can be torn to
accomodate performance. This is C++ with SDL, so unless doing crazy things performance often comes out of the box.

== How to build

----
g++ -o main main.cpp `sdl2-config --libs --cflags` -lSDL2_image
----

== How to run

----
xhost +local:docker
sudo docker run --rm -it -e DISPLAY=${DISPLAY} -v /tmp/.X11-unix:/tmp/.X11-unix -v $(pwd):/home/jim/test sdl2
----

== Binary files format

=== Level

List of tiles indices (in the tileset) as shorts (two bytes per index, little endian). The dimension (i.e. width) of the
level is stored outside of the file. For now.

=== Animations

The _period_ of the animation is the number of tiles making it up. It is stored on one byte. The _duration_ of the
animation is how many ticks pass before the animation goes to the next step / tile. Stored on the next byte. Then are
the tiles indices (in the tileset) as shorts (two bytes per index, little endian).

=== Collisions

Collisions are either rectangles or ellipses which cannot be crossed.

Rectangle collisions are delimitated by an origin (x, y) at the top left of the tile, and a size (width, height). They
are associated with tiles indices. For instance, if tiles are 16x16 pixels, the collision of origin (12, 12) and size
(4, 4) makes a tile not walkable on the square of 4x4 pixels at its bottom right.

Ellipse collisions are delimitated by an ellipse whose center (x, y) is at the top left of the tile, and two radii for
each axis (radiusX, radiusY). As for rectangle collisions, they are associated with tiles indices. For instance, if
tiles are 16x16 pixels, the collision of origin (4, 4) and radii (4, 4) makes a tile not walkable on the circle of 8x8
pixels at its top left.

NOTE: The origin (respectively center) of the rectangle (respectively ellipse) can be outside of the tile. Likewise, the
size of the rectangle or ellipse can be greather than the one of the tile. Consequently, the rectangle or ellipse can
overflow the tile. *However*, the portion outside of the tile will be ignored.

A collision is stored as:

. First two bytes: tile index
. Next byte: collision type (0 for rectangle, 1 for circle)
. Then on the four next bytes (each on one byte): x, y, width, height

All of those are interpreted as unsigned (i.e. positive) integers.

TIP: Several collisions can be added for a single tile index. Every one of those will be checked to determine whether an
object collides with the tile.

== Editor

=== How to use

Move around using the right mouse button. Select a tile to place by left-clicking on it in the tileset view. Place a
tile by left-clicking on a location in the level view. Save the level by pressing `S`. The title bars display a `*` when
the work is not saved.

=== About animations

The editor plays the animations. However be aware that the animations will go out of sync when placing animated tiles
down: the animation starts playing immediately, which means two identical animated tiles can be at a different frame of
animation depending on when they were placed. To synchronize animations, restart the editor.

Note also that the speed of animations can slightly differ from the engine, depending on the performance of the editor.

== TODOs

. Check whether `containerUser` and/or `remoteUser` is/are required in `.devcontainer.json`
. Decide what to do with variable names (type and variable name collisions really is annoying)
. Check whether the built binary can run on a system without libsdl2
. Improve the README: building in docker, development environment, required dependencies for running out of docker, ...
. Navigation to slide along obstacles when possible
. Replace "pixel" by "point" in the code that does not deal with graphics
. Editor: synchronize animated tiles when placing them
. Two layers of tiles
. Editor: resizable tileset window

== Random ideas

. Any QR Code => SHA512 sum => Generate trainer to fight (deterministic)
