= FlatKiss
:1: https://en.wikipedia.org/wiki/KISS_principle

FlatKiss is a 2D tile based toy game engine written in C++.

== Paradigm

First and foremost the mindset driving this project is *_simple_*. It embraces the {1}[KISS] principle. Simplicity comes
before performance / optimization. Simple is different from easy. It is easy to complicate things, but hard to make them
simple. In this project, before implementing anything the question which is asked is: "_Is this simple?_". If it is not,
then revamp it.

Concerns about performance only come after. When the project starts behaving slowly, *then* things can be torn to
accomodate performance. This is C++ with SDL, so unless doing crazy things performance often comes out of the box.

== Terminology

FlatKiss is spelled like this depending on the chosen case:

. FlatKiss
. flatkiss
. FLATKISS

IMPORTANT: No hyphen `-` or underscore `_` in the name, ever.

== Find your way in the documentation

link:doc/architecture.adoc[Architecture]:: Understand how the project works
link:doc/environment.adoc[Environment]:: Setup your environment for development
link:doc/test.adoc[Test]:: Build the project with the CI, find useful resources for testing
link:doc/development.adoc[Development]:: Learn how to start working with the project
link:doc/release.adoc[Release]:: Publish new versions of the project

== Status

I am not actively working on the project. I come back to it from time to time for improving a thing or two. There are
still various issues to address, which can be found in link:doc/development.adoc[Development].
