= Development

How to build the project locally and how to work on it. First follow the instructions in link:environment.adoc[
Environment] to set up the development environment.

== Building

=== Visual Studio Code

If using Docker, or the CMake extension is installed, Visual Studio Code will suggest to configure the project using
CMake the first time the project is opened. After that a _Build_ button becomes available in the bottom bar.

=== CMake

In the root folder of the project, run these commands to configure the project:

----
mkdir build
cd build
cmake ../engine
----

This is only required the first time or when changes are made to CMake files.

NOTE: The directory `build` can have any name.

Then to build the project, run:

----
cmake --build .
----

== Generating the assets

Assets are required for the engine to actually show something.

For demonstrating purposes, sample assets can be generated from the directory `sample-assets/`. To generate them, run:
`./sample-assets/generators/generate_assets.py`. An `assets/` directory is created containing the assets. Note that it
will download pictures which must be converted manually to the BMP file format.

TIP: The sample assets are stored as text for easier debugging. However as described in link:architecture.adoc[
Architecture], the engine expects them to be in binary form, so they must be converted. The command described above does
just that.

== Running

NOTE: As of now it is not possible to run the generated program in the Docker container (the image cannot run graphic
apps and is not configured to forward to an external X server), nor from Visual Studio Code (it is lacking launch
configuration).

From the root folder of the project, run: `./build/flatkiss/flatkiss-bin`.

NOTE: Replace `build` with the name given in the previous section if it is different.

IMPORTANT: The directory containing the assets must be in the directory from where the program is ran. In this example,
this is the root directory of the project.
